# Day_5 Python_from_Scratch
# List
print("List is a sequence data type In python that Stores data of different primitve data types.")
print("A list is represented by Variable_name= [ ] , and the values in the [] braces seperated by a comma are counted as a single element.")
print("A list elements can be of similar or different data types. All the elements can be accessed using indexing Similar to String.")
List_1=["Prabhat","Ayush","Ankush"]
print("Here the List_1 =",List_1)
print("An empty list is created as - var=[] or var=list()")

# Indexing in List - 

print("The indexing is done as :")
print("\t\tPrabhat\tAyush\tAnkush")
print("\t\t   0   \t  1  \t   2")
print("\t\t  -3   \t -2  \t  -1")
print("Accessing Elements using Index as - ")
print("List_1[0] is",List_1[0],"\nList_1[2] is",List_1[2])
print("List_1[-3] is",List_1[-3],"\nList_1[-1] is",List_1[-1])

# Slicing in List -

print("Slicing in List is very much similar to slicing in Strings.")
print("We can access a part of List using slicing using List-name[Starting Index : Ending index].\nThe ending index is excluded.")
print("For example -\nList_1[0:2] is :",List_1[0:2])
print("List_1[-3:-1] is :",List_1[-3:-1])
print("If any index is not available in slicing, the terminal value is default.")
print("List_1[:3] is :",List_1[:3])
print("List_1[1:] is :",List_1[1:])

# Methods in List-

print("List has also various methods:")
print("\ta)len() method is used to find the length of the List.")
print("\t len(List_1) is ",len(List_1),"\n")
print("\tb)count(arg) method is used to count the occurence of an element in List.")
print("\t List_1.count(\"Prabhat\") is ",List_1.count("Prabhat"),"\n")
print("\tc)sort() method is used to sort the List.Default order is ascending.")
List_1.sort()
print("\t After sorting List_1 is ",List_1,"\n")
print("\td)sort(reverse=True) method is used to sort the List in reverse order.")
List_1.sort(reverse=True)
print("\t After sorting in reverse order List_1 is ",List_1,"\n")
print("\te)index(arg) method is used to find the first index of an element in List.")
print("\t List_1.index(\"Prabhat\") is ",List_1.index("Prabhat"),"\n")
print("\tf)reverse() method is used to reverse the order of elements of the List.")
List_1.reverse()
print("\t After reversing List_1 is ",List_1,"\n")
print("\tg)min(arg) method is used to find minimum element of the List.")
print("\t Minimum element of the List_1 is min(List_1) :",min(List_1),"\n")
print("\th)max(arg) method is used to find maximum element of the List.")
print("\t Maximum element of the List_1 is max(List_1) :",max(List_1),"\n")
print("\ti)sum(arg) method is used to find sum of element of the List.")
# print("\t Sum of the elements of the List_1 is sum(List_1) =",sum(List_1),"\n")
print("\tj)append(arg) method is used to add element in the List at the end.")
List_1.append("Shivam")
print("\t List_1 after List_1.append(\"Shivam\") is :",List_1,"\n")
print("\tk)insert(arg_1,arg_2) method is used to insert element at the desired index in the List.")
List_1.insert(3,"Vivek")
print("\t List_1 after inserting Vivek at index 3 , List_1 is :",List_1,"\n")
print("\tl)pop(arg_1) method is used to pop element from the List.")
print("\t List_1.pop(3) is :",List_1.pop(3),"\n")
print("\t if index is not given , pop() will pop the last item of the list. As List_1.pop() is :",List_1.pop(),"\n")
print("\tm)del(arg) method is used to delete element from the List at required index.")
del(List_1[0])
print("\t After deleting List_1[0] from List_1 , List_1 is :",List_1,"\n")
print("\tn)remove(arg) method is used to remove element by value from the List.")
List_1.remove("Prabhat")
print("\t After removing \"Prabhat\" from List_1 , List_1 is :",List_1,"\n")
print("\to)extend(arg) method is used to extend the List with other iterative data types like list and tuples.")
List_2=["Ankush","Vivek","Prabhat","Shivam"]
print("\t List_2 is :",List_2)
List_1.extend(List_2)
print("\t After extending List_1 with List_2, List_1 is :",List_1,"\n" )
print("\tp)copy() method is used to copy all the  elements from a List to another List.")
List_3=List_1.copy()
print("\t After copying to List_3 from List_1 , List_3 is :",List_3,"\n")
print("\tq)clear() method is used to clear all the  elements of a List.")
List_3.clear()
print("\t After clearing the List_3 , List_3 is :",List_3)